import {SkeletonLib} from "./types";
import {
  TradeSkeleton,
  SearchSkeleton,
  ReportSkeleton,
  MessageSkeleton,
  ListItemSkeleton,
  FeedbackSkeleton,
  OfferSentSkeleton,
  HomeScreenSkeleton,
  SentScreenSkeleton,
  InboxScreenSkeleton,
  TradeScreenSkeleton,
  SearchAlertSkeleton,
  OfferScreenSkeleton,
  TradesScreenSkeleton,
  ConversationSkeleton,
  SearchScreenSkeleton,
  OfferReceivedSkeleton,
  ProfileScreenSkeleton,
  ProductScreenSkeleton,
  TrendingManagerSkeleton,
  ProductListItemSkeleton,
  UserPresentationSkeleton,
  MyInventoryScreenSkeleton,
  TodayTrendingScreenSkeleton,
} from "./lib";

export const Skeleton: SkeletonLib = {
  Trade: TradeSkeleton,
  Report: ReportSkeleton,
  Search: SearchSkeleton,
  Message: MessageSkeleton,
  Feedback: FeedbackSkeleton,
  ListItem: ListItemSkeleton,
  OfferSent: OfferSentSkeleton,
  SentScreen: SentScreenSkeleton,
  HomeScreen: HomeScreenSkeleton,
  InboxScreen: InboxScreenSkeleton,
  SearchAlert: SearchAlertSkeleton,
  TradeScreen: TradeScreenSkeleton,
  OfferScreen: OfferScreenSkeleton,
  Conversation: ConversationSkeleton,
  TradesScreen: TradesScreenSkeleton,
  SearchScreen: SearchScreenSkeleton,
  ProfileScreen: ProfileScreenSkeleton,
  ProductScreen: ProductScreenSkeleton,
  OfferReceived: OfferReceivedSkeleton,
  TrendingManager: TrendingManagerSkeleton,
  ProductListItem: ProductListItemSkeleton,
  UserPresentation: UserPresentationSkeleton,
  MyInventoryScreen: MyInventoryScreenSkeleton,
  TodayTrendingScreen: TodayTrendingScreenSkeleton,
};
